[variables]
NIXPACKS_PKGS_ARCHIVE = "https://github.com/NixOS/nixpkgs/archive/refs/heads/nixos-24.11.tar.gz"

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
